name: Release
on:
  push:
    tags:
      - "**"

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: make
      - name: version
        run: echo "::set-output name=version::$(./build/sorter --version)"
        id: version
      - name: release
        uses: elgohr/Github-Release-Action@v4
        id: create_release
        with:
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ github.token }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ./build/sorter.linux-amd64.tar.gz
            asset_name: sorter.linux-amd64.tar.gz
            asset_content_type: application/gzip
